name: PSPalatro CI Build

on:
  push:
    branches: [ main, master, Test ] # Triggers on push to these branches
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger from the GitHub UI

jobs:
  build:
    # Use the official Ubuntu runner for cross-compilation
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 2. Download and Extract PSPSDK
        # Download the pre-built PSPDEV archive
        run: |
          wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz
          tar -xvf pspdev-ubuntu-latest-x86_64.tar.gz

      - name: 3. Setup PSPDEV Environment
        # Set the required PSPDEV environment variable for all subsequent steps
        run: |
          echo "PSPDEV=$HOME/pspdev" >> $GITHUB_ENV
          # Although we set GITHUB_PATH in the next step, we'll use the absolute path for robustness.
          
      - name: 4. Install Project Dependencies (FIXED)
        # *** FIX: Calling psp-pacman using its explicit absolute path ***
        run: |
          $HOME/pspdev/bin/psp-pacman -S libzip vorbis liblzma stb --noconfirm

      - name: 5. Build PSPalatro
        # Ensure the compiler can find the tools by adding PSPDEV/bin to PATH for this step
        run: |
          export PATH="$PATH:$PSPDEV/bin"
          make

      - name: 6. Create Artifact Archive
        # Bundle the required files (EBOOT.PBP and assets) into a zip
        run: |
          mkdir pspalatro_release
          cp EBOOT.PBP pspalatro_release/
          cp -r assets/ pspalatro_release/
          zip -r pspalatro_release.zip pspalatro_release/

      - name: 7. Upload Build Artifact
        # Upload the zip file as a downloadable artifact on GitHub
        uses: actions/upload-artifact@v4
        with:
          name: PSPalatro_EBOOT
          path: pspalatro_release.zip
          retention-days: 5 # How long the artifact is kept
